== 지출 API
:operation-http-request-title: HTTP Request
:operation-request-body-title: Request Body
:operation-request-fields-title: Request Fields
:operation-response-body-title: Response Body
:operation-response-fields-data-title: Response Fields
:operation-query-parameters-title: Query Parameters

=== 지출 생성 API
==== `POST /api/expenditures`
operation::expenditure-controller-test/create-expenditure[snippets="request-body,request-fields,response-body,response-fields-data"]

=== 지출 수정 API
==== `PUT /api/expenditures/{expenditureId}`
operation::expenditure-controller-test/update-expenditure[snippets="request-body,request-fields,response-body"]

=== 지출 상세 조회 API
==== `GET /api/expenditures/{expenditureId}`
operation::expenditure-controller-test/get-expenditure-details[snippets="response-body,response-fields-data"]

=== 지출 삭제 API
==== `DELETE /api/expenditures/{expenditureId}`
operation::expenditure-controller-test/delete-expenditure[snippets="response-body"]

=== 지출 목록 조회 API
==== `GET /api/expenditures`
operation::expenditure-controller-test/search-expenditure[snippets="http-request,query-parameters,response-body,response-fields-data"]

=== 지출 합계 제외 API
==== `GET /api/expenditures/excepts`
operation::expenditure-controller-test/search-expenditure-excepts[snippets="http-request,query-parameters,response-body,response-fields-data"]