== 지출 API

=== 지출 상세 조회 API
==== `GET /api/expenditures/{expenditureId}`

- `지출` 을 생성한 유저만 권한

operation::expenditure-controller-test/get-expenditure-details[snippets="response-body,response-fields-data"]

=== 지출 목록 조회 API
==== `GET /api/expenditures`

- `지출` 을 생성한 유저만 권한
- 조회된 모든 내용의 `지출 합계`, `카테고리 별 지출 합계` 반환
- `지출일`, `지출 금액`, `지출 id` 를 기준으로 내림차순 정렬

operation::expenditure-controller-test/search-expenditure[snippets="http-request,query-parameters,response-body,response-fields-data"]

=== 지출 합계 제외 API
==== `GET /api/expenditures/excepts`

- `지출` 을 생성한 유저만 권한
- `합계 제외` 처리한 지출은 목록에 포함되지만, 모든 `지출 합계` 에서는 제외

operation::expenditure-controller-test/search-expenditure-excepts[snippets="http-request,query-parameters,response-body,response-fields-data"]

=== 지출 생성 API
==== `POST /api/expenditures`

- 해당 지출 내역의 카테고리 유효성 검사 수행 (존재하는 카테고리인지, `카테고리 id` 와 `type` 이 일치하는지)

operation::expenditure-controller-test/create-expenditure[snippets="request-body,request-fields,response-body,response-fields-data"]

=== 지출 수정 API
==== `PUT /api/expenditures/{expenditureId}`

- `지출` 을 생성한 유저만 권한
- 해당 지출 내역의 카테고리 유효성 검사 수행 (존재하는 카테고리인지, `카테고리 id` 와 `type` 이 일치하는지)

operation::expenditure-controller-test/update-expenditure[snippets="request-body,request-fields,response-body"]

=== 지출 삭제 API
==== `DELETE /api/expenditures/{expenditureId}`

- `지출` 을 생성한 유저만 권한
- **Soft Delete** 수행

operation::expenditure-controller-test/delete-expenditure[snippets="response-body"]

=== 지출 통계 API
==== `GET /api/expenditures/stats`

- 오늘 날짜를 기준으로 통계 생성
- `지난 년도`, `지난 달`, `지난 주` 대비 `총액`, `카테고리 별` 소비율
- `지난 년도`: 현재 `2023-12-06` 이라면, `2022-01-01 ~ 2022-12-06` 대비 `2023-01-01 ~ 2023-12-06` 소비율
- `지난 달`: 현재 `2023-12-06` 이라면, `2023-11-01 ~ 2023-11-06` 대비 `2023-12-01 ~ 2023-12-06` 소비율
- `지난 주`: 현재 `2023-12-06` 이라면, `2023-11-27 ~ 2023-11-29` 대비 `2023-12-04 ~ 2023-12-06` 소비율 (한 주는 `월 ~ 일`)

operation::expenditure-controller-test/produce-expenditure-stats[snippets="http-request,query-parameters,response-body,response-fields-data"]

=== 오늘 지출 추천 API
==== `GET /api/expenditures/consult`

- 설정한 월별 예산을 만족하기 위해 오늘 지출 가능한 금액을 `총액` 과 `카테고리 별 금액` 으로 제공
- `절약하여 소비한 경우`, `예산에 맞게 소비한 경우`, `예산 초과 위험이 있는 경우`, `현재까지의 지출이 예산을 초과한 경우` 등 유저의 상황에 맞는 메세지를 같이 노출 ex. `EXCELLENT`, `GOOD`, `WARN`, `BAD`
- `15333원` 같은 값이라면 백원 단위 반올림으로 사용자 친화적으로 변환
- 특정 시간에 Discord webhook, 이메일, 카카오톡 등 알림 발송 (추후 구현 예정)
- 유저가 직접 요청하는 API가 아닌 스케줄러 등 서버 내부적으로 요청하는 API

operation::expenditure-controller-test/consult-today-expenditure[snippets="response-body,response-fields-data"]

=== 오늘 지출 안내 API
==== `GET /api/expenditures/daily-stats`

- 오늘 지출한 내용을 `총액` 과 `카테고리 별 금액` 으로 조회
- 월별 설정한 예산 기준 `카테고리 별 통계` 제공
- 카테고리 별 오늘 `적정 금액`: 오늘 사용했으면 적절했을 금액
- 카테고리 별 오늘 `지출 금액`: 오늘 실제로 사용한 금액
- `소비율`: 카테고리 별 적정 지출 금액 대비 실제 지출 금액의 비율을 의미 (% 단위)
- 특정 시간에 Discord webhook, 이메일, 카카오톡 등 알림 발송 (추후 구현 예정)
- 유저가 직접 요청하는 API가 아닌 스케줄러 등 서버 내부적으로 요청하는 API

operation::expenditure-controller-test/produce-today-expenditure-daily-stats[snippets="response-body,response-fields-data"]